export const SIGNIN_USER_REQUEST = 'SIGNIN_USER_REQUEST'; 
export const SIGNIN_USER_SUCCESS = 'SIGNIN_USER_SUCCESS'; 
export const SIGNIN_USER_FAILED = 'SIGNIN_USER_FAILED'; 

export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST'; 
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'; 
export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED'; 

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'; 
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'; 
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED'; 

export const LOGOUT_USER = 'LOGOUT_USER';