export const LIST_PRODUCT_REQUEST = 'LIST_PRODUCT_REQUEST';
export const LIST_PRODUCT_SUCCESS = 'LIST_PRODUCT_SUCCESS';
export const LIST_PRODUCT_FAILED = 'LIST_PRODUCT_FAILED';

export const DETAILS_PRODUCT_REQUEST = 'DETAILS_PRODUCT_REQUEST';
export const DETAILS_PRODUCT_SUCCESS = 'DETAILS_PRODUCT_SUCCESS';
export const DETAILS_PRODUCT_FAILED = 'DETAILS_PRODUCT_FAILED';

export const SAVE_PRODUCT_REQUEST = 'SAVE_PRODUCT_REQUEST';
export const SAVE_PRODUCT_SUCCESS = 'SAVE_PRODUCT_SUCCESS';
export const SAVE_PRODUCT_FAILED = 'SAVE_PRODUCT_FAILED';

export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAILED = 'DELETE_PRODUCT_FAILED';