export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAILED = 'CREATE_ORDER_FAILED';

export const DETAILS_ORDER_REQUEST = 'DETAILS_ORDER_REQUEST';
export const DETAILS_ORDER_SUCCESS = 'DETAILS_ORDER_SUCCESS';
export const DETAILS_ORDER_FAILED = 'DETAILS_ORDER_FAILED';

export const PAY_ORDER_REQUEST = 'PAY_ORDER_REQUEST';
export const PAY_ORDER_SUCCESS = 'PAY_ORDER_SUCCESS';
export const PAY_ORDER_FAILED = 'PAY_ORDER_FAILED';

export const MY_ORDER_LIST_REQUEST = 'MY_ORDER_LIST_REQUEST';
export const MY_ORDER_LIST_SUCCESS = 'MY_ORDER_LIST_SUCCESS';
export const MY_ORDER_LIST_FAILED = 'MY_ORDER_LIST_FAILED';

export const LIST_ORDER_REQUEST = 'LIST_ORDER_REQUEST';
export const LIST_ORDER_SUCCESS = 'LIST_ORDER_SUCCESS';
export const LIST_ORDER_FAILED = 'LIST_ORDER_FAILED';

export const DELETE_ORDER_REQUEST = 'DELETE_ORDER_REQUEST';
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS';
export const DELETE_ORDER_FAILED = 'DELETE_ORDER_FAILED';
